graph TD
subgraph 開発環境 - Ubuntu 16.04.1 LTS
  A1("# package<br />
  # Java8 (Android SDK環境が整っていれば不要)<br />
  add-apt-repository #quot;deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main#quot;<br />
  apt-get update<br />
  add-apt-repository ppa:webupd8team/y-ppa-manager<br />
  apt-get install oracle-java8-installer<br />
  <br />
  # TensorFlow Android Interface ライブラリ作成用<br />
  apt-get install git \<br />
  automake \<br />
  libtool \<br />
  zlib1g-dev")
  A2("# Android SDK (Android Studioでもok)<br />
export ${ANDROID_HOME}=$HOME/Android/Sdk<br />
export ${NDK_ROOT}=${ANDROID_HOME}/ndk-bundle<br />
${ANDROID_HOME}/tools/bin/sdkmanager \<br />
#quot;build-tools;24.0.2#quot; \<br />
ndk-bundle \<br />
tools \<br />
#quot;platforms;android-24#quot; \<br />
#quot;platforms;android-21#quot; \<br />
cmake3.6.3155560 ")
  S1((環境構築済み))
end
subgraph TensorFlow Android Interface ライブラリ作成
  S2{どれか}
  B1(build_all_android.shで<br>TensorFlowのライブラリ作成)
  B2(bazelで<br>TensorFlowのライブラリ作成)
end
subgraph Androidアプリ作成
  D1(Android Studioのプロジェクトに組み込む)
end
subgraph Androidアプリ作成
  D2(Android Studioのプロジェクトに組み込む)
end

style B1 fill:#f9f,stroke:#333,stroke-width:4px;
style D1 fill:#f9f,stroke:#333,stroke-width:4px;

A1-->S1
A2-->S1
S1-->S2
S2-->B1
S2-->B2
B1-->D1
B2-->D2
